project_id = "bwmkqscqkfoezcuzgpwq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv6"
port = 54323
max_header_length = 4096

[storage]
enabled = true
port = 54324
file_size_limit = "50MiB"
buckets = []

[auth]
enabled = true
port = 54325
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"

[edge_functions]
enabled = true
port = 54326

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[functions.close-shift]
verify_jwt = false

[functions.repair-inventory-system]
verify_jwt = false