// Complete 61 Recipe Data
const recipeData = [
  { recipe_name: "Matcha Blended", recipe_category: "Blended", ingredient_name: "Frappe Powder", quantity: 30, unit: "grams", cost_per_unit: 0.24, suggested_price: 90 },
  { recipe_name: "Matcha Blended", recipe_category: "Blended", ingredient_name: "Matcha Powder", quantity: 30, unit: "grams", cost_per_unit: 0.82, suggested_price: 90 },
  { recipe_name: "Matcha Blended", recipe_category: "Blended", ingredient_name: "Milk", quantity: 150, unit: "ml", cost_per_unit: 0.09, suggested_price: 90 },
  { recipe_name: "Matcha Blended", recipe_category: "Blended", ingredient_name: "16oz Plastic Cups", quantity: 1, unit: "piece", cost_per_unit: 8, suggested_price: 90 },
  { recipe_name: "Matcha Blended", recipe_category: "Blended", ingredient_name: "Bending Straw", quantity: 1, unit: "piece", cost_per_unit: 1, suggested_price: 90 },
  { recipe_name: "Matcha Blended", recipe_category: "Blended", ingredient_name: "Flat Lid", quantity: 1, unit: "piece", cost_per_unit: 1, suggested_price: 90 },
  { recipe_name: "Oreo Strawberry Blended", recipe_category: "Blended", ingredient_name: "Frappe Powder", quantity: 30, unit: "grams", cost_per_unit: 0.24, suggested_price: 110 },
  { recipe_name: "Oreo Strawberry Blended", recipe_category: "Blended", ingredient_name: "Strawberry Syrup", quantity: 30, unit: "ml", cost_per_unit: 1.25, suggested_price: 110 },
  { recipe_name: "Oreo Strawberry Blended", recipe_category: "Blended", ingredient_name: "Oreo Cookie", quantity: 1, unit: "piece", cost_per_unit: 2, suggested_price: 110 },
  { recipe_name: "Oreo Strawberry Blended", recipe_category: "Blended", ingredient_name: "Crushed Oreo", quantity: 2, unit: "portion", cost_per_unit: 2, suggested_price: 110 },
  { recipe_name: "Oreo Strawberry Blended", recipe_category: "Blended", ingredient_name: "16oz Plastic Cups", quantity: 1, unit: "piece", cost_per_unit: 8, suggested_price: 110 },
  { recipe_name: "Oreo Strawberry Blended", recipe_category: "Blended", ingredient_name: "Flat Lid", quantity: 1, unit: "piece", cost_per_unit: 1, suggested_price: 110 },
  { recipe_name: "Oreo Strawberry Blended", recipe_category: "Blended", ingredient_name: "Bending Straw", quantity: 1, unit: "piece", cost_per_unit: 1, suggested_price: 110 },
  { recipe_name: "Oreo Strawberry Blended", recipe_category: "Blended", ingredient_name: "Milk", quantity: 200, unit: "ml", cost_per_unit: 0.05, suggested_price: 110 },
  { recipe_name: "Strawberry Kiss Blended", recipe_category: "Blended", ingredient_name: "Strawberry Syrup", quantity: 30, unit: "ml", cost_per_unit: 0.45, suggested_price: 110 },
  { recipe_name: "Strawberry Kiss Blended", recipe_category: "Blended", ingredient_name: "Frappe Powder", quantity: 30, unit: "grams", cost_per_unit: 0.24, suggested_price: 110 },
  { recipe_name: "Strawberry Kiss Blended", recipe_category: "Blended", ingredient_name: "Choco Flakes", quantity: 3, unit: "portion", cost_per_unit: 2.5, suggested_price: 110 },
  { recipe_name: "Strawberry Kiss Blended", recipe_category: "Blended", ingredient_name: "Milk", quantity: 150, unit: "ml", cost_per_unit: 0.09, suggested_price: 110 },
  { recipe_name: "Strawberry Kiss Blended", recipe_category: "Blended", ingredient_name: "16oz Plastic Cups", quantity: 1, unit: "piece", cost_per_unit: 8, suggested_price: 110 },
  { recipe_name: "Strawberry Kiss Blended", recipe_category: "Blended", ingredient_name: "Flat Lid", quantity: 1, unit: "piece", cost_per_unit: 1, suggested_price: 110 },
  { recipe_name: "Strawberry Kiss Blended", recipe_category: "Blended", ingredient_name: "Bending Straw", quantity: 1, unit: "piece", cost_per_unit: 1, suggested_price: 110 },
  { recipe_name: "Caramel Delight Croffle", recipe_category: "Classic", ingredient_name: "Regular Croissant", quantity: 1, unit: "piece", cost_per_unit: 15, suggested_price: 125 },
  { recipe_name: "Caramel Delight Croffle", recipe_category: "Classic", ingredient_name: "Whipped Cream", quantity: 1, unit: "serving", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Caramel Delight Croffle", recipe_category: "Classic", ingredient_name: "Caramel Sauce", quantity: 1, unit: "portion", cost_per_unit: 1.25, suggested_price: 125 },
  { recipe_name: "Caramel Delight Croffle", recipe_category: "Classic", ingredient_name: "Colored Sprinkles", quantity: 1, unit: "portion", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Caramel Delight Croffle", recipe_category: "Classic", ingredient_name: "Chopstick", quantity: 1, unit: "pair", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Caramel Delight Croffle", recipe_category: "Classic", ingredient_name: "Wax Paper", quantity: 1, unit: "piece", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Choco Marshmallow Croffle", recipe_category: "Classic", ingredient_name: "Regular Croissant", quantity: 1, unit: "piece", cost_per_unit: 15, suggested_price: 125 },
  { recipe_name: "Choco Marshmallow Croffle", recipe_category: "Classic", ingredient_name: "Whipped Cream", quantity: 1, unit: "serving", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Choco Marshmallow Croffle", recipe_category: "Classic", ingredient_name: "Chocolate Sauce", quantity: 1, unit: "portion", cost_per_unit: 1.75, suggested_price: 125 },
  { recipe_name: "Choco Marshmallow Croffle", recipe_category: "Classic", ingredient_name: "Marshmallow", quantity: 1, unit: "portion", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Choco Marshmallow Croffle", recipe_category: "Classic", ingredient_name: "Chopstick", quantity: 2, unit: "pair", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Choco Marshmallow Croffle", recipe_category: "Classic", ingredient_name: "Wax Paper", quantity: 1, unit: "piece", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Choco Nut Croffle", recipe_category: "Classic", ingredient_name: "Regular Croissant", quantity: 1, unit: "piece", cost_per_unit: 15, suggested_price: 125 },
  { recipe_name: "Choco Nut Croffle", recipe_category: "Classic", ingredient_name: "Whipped Cream", quantity: 1, unit: "serving", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Choco Nut Croffle", recipe_category: "Classic", ingredient_name: "Chocolate Sauce", quantity: 1, unit: "portion", cost_per_unit: 1.75, suggested_price: 125 },
  { recipe_name: "Choco Nut Croffle", recipe_category: "Classic", ingredient_name: "Peanut", quantity: 1, unit: "portion", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Choco Nut Croffle", recipe_category: "Classic", ingredient_name: "Chopstick", quantity: 1, unit: "pair", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Choco Nut Croffle", recipe_category: "Classic", ingredient_name: "Wax Paper", quantity: 1, unit: "piece", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Tiramisu Croffle", recipe_category: "Classic", ingredient_name: "Regular Croissant", quantity: 1, unit: "piece", cost_per_unit: 15, suggested_price: 125 },
  { recipe_name: "Tiramisu Croffle", recipe_category: "Classic", ingredient_name: "Whipped Cream", quantity: 1, unit: "serving", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Tiramisu Croffle", recipe_category: "Classic", ingredient_name: "Tiramisu", quantity: 1, unit: "portion", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Tiramisu Croffle", recipe_category: "Classic", ingredient_name: "Choco Flakes", quantity: 1, unit: "portion", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Tiramisu Croffle", recipe_category: "Classic", ingredient_name: "Chopstick", quantity: 1, unit: "pair", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Tiramisu Croffle", recipe_category: "Classic", ingredient_name: "Wax Paper", quantity: 1, unit: "piece", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Iced Tea", recipe_category: "Cold", ingredient_name: "Iced Tea Powder", quantity: 10, unit: "grams", cost_per_unit: 0.02, suggested_price: 60 },
  { recipe_name: "Iced Tea", recipe_category: "Cold", ingredient_name: "16oz Plastic Cups", quantity: 1, unit: "piece", cost_per_unit: 8, suggested_price: 60 },
  { recipe_name: "Iced Tea", recipe_category: "Cold", ingredient_name: "Flat Lid", quantity: 1, unit: "piece", cost_per_unit: 1, suggested_price: 60 },
  { recipe_name: "Iced Tea", recipe_category: "Cold", ingredient_name: "Bending Straw", quantity: 1, unit: "piece", cost_per_unit: 1, suggested_price: 60 },
  { recipe_name: "Lemonade", recipe_category: "Cold", ingredient_name: "Lemonade Powder", quantity: 10, unit: "grams", cost_per_unit: 1, suggested_price: 60 },
  { recipe_name: "Lemonade", recipe_category: "Cold", ingredient_name: "16oz Plastic Cups", quantity: 1, unit: "piece", cost_per_unit: 8, suggested_price: 60 },
  { recipe_name: "Lemonade", recipe_category: "Cold", ingredient_name: "Flat Lid", quantity: 1, unit: "piece", cost_per_unit: 1, suggested_price: 60 },
  { recipe_name: "Lemonade", recipe_category: "Cold", ingredient_name: "Bending Straw", quantity: 1, unit: "piece", cost_per_unit: 1, suggested_price: 60 },
  { recipe_name: "Vanilla Caramel Iced", recipe_category: "Cold", ingredient_name: "Vanilla Syrup", quantity: 10, unit: "ml", cost_per_unit: 0.45, suggested_price: 90 },
  { recipe_name: "Vanilla Caramel Iced", recipe_category: "Cold", ingredient_name: "Monalisa", quantity: 5, unit: "ml", cost_per_unit: 0.2, suggested_price: 90 },
  { recipe_name: "Vanilla Caramel Iced", recipe_category: "Cold", ingredient_name: "Caramel Syrup", quantity: 15, unit: "ml", cost_per_unit: 0.35, suggested_price: 90 },
  { recipe_name: "Vanilla Caramel Iced", recipe_category: "Cold", ingredient_name: "Milk", quantity: 150, unit: "ml", cost_per_unit: 0.09, suggested_price: 90 },
  { recipe_name: "Vanilla Caramel Iced", recipe_category: "Cold", ingredient_name: "16oz Plastic Cups", quantity: 1, unit: "piece", cost_per_unit: 8, suggested_price: 90 },
  { recipe_name: "Vanilla Caramel Iced", recipe_category: "Cold", ingredient_name: "Bending Straw", quantity: 1, unit: "piece", cost_per_unit: 1, suggested_price: 90 },
  { recipe_name: "Vanilla Caramel Iced", recipe_category: "Cold", ingredient_name: "Flat Lid", quantity: 1, unit: "piece", cost_per_unit: 1, suggested_price: 90 },
  { recipe_name: "Americano Hot", recipe_category: "Espresso", ingredient_name: "16Oz Hot Cups", quantity: 1, unit: "piece", cost_per_unit: 6, suggested_price: 65 },
  { recipe_name: "Americano Hot", recipe_category: "Espresso", ingredient_name: "Espresso Shot", quantity: 30, unit: "ml", cost_per_unit: 2.5, suggested_price: 65 },
  { recipe_name: "Americano Hot", recipe_category: "Espresso", ingredient_name: "Coffee Lid", quantity: 1, unit: "piece", cost_per_unit: 1, suggested_price: 65 },
  { recipe_name: "Americano Iced", recipe_category: "Espresso", ingredient_name: "Espresso Shot", quantity: 30, unit: "ml", cost_per_unit: 2.5, suggested_price: 70 },
  { recipe_name: "Americano Iced", recipe_category: "Espresso", ingredient_name: "16oz Plastic Cups", quantity: 1, unit: "piece", cost_per_unit: 8, suggested_price: 70 },
  { recipe_name: "Americano Iced", recipe_category: "Espresso", ingredient_name: "Flat Lid", quantity: 1, unit: "piece", cost_per_unit: 1, suggested_price: 70 },
  { recipe_name: "Cafe Latte Hot", recipe_category: "Espresso", ingredient_name: "Espresso Shot", quantity: 30, unit: "ml", cost_per_unit: 2.5, suggested_price: 65 },
  { recipe_name: "Cafe Latte Hot", recipe_category: "Espresso", ingredient_name: "16Oz Hot Cups", quantity: 1, unit: "piece", cost_per_unit: 6, suggested_price: 65 },
  { recipe_name: "Cafe Latte Hot", recipe_category: "Espresso", ingredient_name: "Milk", quantity: 180, unit: "ml", cost_per_unit: 0.05, suggested_price: 65 },
  { recipe_name: "Cafe Latte Hot", recipe_category: "Espresso", ingredient_name: "Coffee Lid", quantity: 1, unit: "piece", cost_per_unit: 1, suggested_price: 65 },
  { recipe_name: "Cafe Latte Iced", recipe_category: "Espresso", ingredient_name: "Espresso Shot", quantity: 30, unit: "ml", cost_per_unit: 2.5, suggested_price: 70 },
  { recipe_name: "Cafe Latte Iced", recipe_category: "Espresso", ingredient_name: "Milk", quantity: 180, unit: "ml", cost_per_unit: 0.05, suggested_price: 70 },
  { recipe_name: "Cafe Latte Iced", recipe_category: "Espresso", ingredient_name: "16oz Plastic Cups", quantity: 1, unit: "piece", cost_per_unit: 8, suggested_price: 70 },
  { recipe_name: "Cafe Latte Iced", recipe_category: "Espresso", ingredient_name: "Flat Lid", quantity: 1, unit: "piece", cost_per_unit: 1, suggested_price: 70 },
  { recipe_name: "Cafe Mocha Hot", recipe_category: "Espresso", ingredient_name: "Espresso Shot", quantity: 30, unit: "ml", cost_per_unit: 2.5, suggested_price: 65 },
  { recipe_name: "Cafe Mocha Hot", recipe_category: "Espresso", ingredient_name: "16Oz Hot Cups", quantity: 1, unit: "piece", cost_per_unit: 6, suggested_price: 65 },
  { recipe_name: "Cafe Mocha Hot", recipe_category: "Espresso", ingredient_name: "Chocolate Syrup", quantity: 15, unit: "ml", cost_per_unit: 1.25, suggested_price: 65 },
  { recipe_name: "Cafe Mocha Hot", recipe_category: "Espresso", ingredient_name: "Milk", quantity: 150, unit: "ml", cost_per_unit: 0.05, suggested_price: 65 },
  { recipe_name: "Cafe Mocha Hot", recipe_category: "Espresso", ingredient_name: "Coffee Lid", quantity: 1, unit: "piece", cost_per_unit: 1, suggested_price: 65 },
  { recipe_name: "Cafe Mocha Iced", recipe_category: "Espresso", ingredient_name: "Espresso Shot", quantity: 30, unit: "ml", cost_per_unit: 2.5, suggested_price: 70 },
  { recipe_name: "Cafe Mocha Iced", recipe_category: "Espresso", ingredient_name: "Chocolate Syrup", quantity: 15, unit: "ml", cost_per_unit: 1.25, suggested_price: 70 },
  { recipe_name: "Cafe Mocha Iced", recipe_category: "Espresso", ingredient_name: "Milk", quantity: 150, unit: "ml", cost_per_unit: 0.05, suggested_price: 70 },
  { recipe_name: "Cafe Mocha Iced", recipe_category: "Espresso", ingredient_name: "16oz Plastic Cups", quantity: 1, unit: "piece", cost_per_unit: 8, suggested_price: 70 },
  { recipe_name: "Cafe Mocha Iced", recipe_category: "Espresso", ingredient_name: "Flat Lid", quantity: 1, unit: "piece", cost_per_unit: 1, suggested_price: 70 },
  { recipe_name: "Cappuccino Hot", recipe_category: "Espresso", ingredient_name: "Espresso Shot", quantity: 30, unit: "ml", cost_per_unit: 2.5, suggested_price: 65 },
  { recipe_name: "Cappuccino Hot", recipe_category: "Espresso", ingredient_name: "Milk", quantity: 120, unit: "ml", cost_per_unit: 0.05, suggested_price: 65 },
  { recipe_name: "Cappuccino Hot", recipe_category: "Espresso", ingredient_name: "Milk", quantity: 30, unit: "ml", cost_per_unit: 0.05, suggested_price: 65 },
  { recipe_name: "Cappuccino Hot", recipe_category: "Espresso", ingredient_name: "16Oz Hot Cups", quantity: 1, unit: "piece", cost_per_unit: 6, suggested_price: 65 },
  { recipe_name: "Cappuccino Hot", recipe_category: "Espresso", ingredient_name: "Coffee Lid", quantity: 1, unit: "piece", cost_per_unit: 1, suggested_price: 65 },
  { recipe_name: "Cappuccino Iced", recipe_category: "Espresso", ingredient_name: "Espresso Shot", quantity: 30, unit: "ml", cost_per_unit: 2.5, suggested_price: 70 },
  { recipe_name: "Cappuccino Iced", recipe_category: "Espresso", ingredient_name: "Milk", quantity: 120, unit: "ml", cost_per_unit: 0.05, suggested_price: 70 },
  { recipe_name: "Cappuccino Iced", recipe_category: "Espresso", ingredient_name: "16oz Plastic Cups", quantity: 1, unit: "piece", cost_per_unit: 8, suggested_price: 70 },
  { recipe_name: "Cappuccino Iced", recipe_category: "Espresso", ingredient_name: "Flat Lid", quantity: 1, unit: "piece", cost_per_unit: 1, suggested_price: 70 },
  { recipe_name: "Blueberry Croffle", recipe_category: "Fruity", ingredient_name: "Regular Croissant", quantity: 1, unit: "piece", cost_per_unit: 15, suggested_price: 125 },
  { recipe_name: "Blueberry Croffle", recipe_category: "Fruity", ingredient_name: "Whipped Cream", quantity: 1, unit: "serving", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Blueberry Croffle", recipe_category: "Fruity", ingredient_name: "Blueberry Jam", quantity: 1, unit: "scoop", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Blueberry Croffle", recipe_category: "Fruity", ingredient_name: "Crushed Grahams", quantity: 1, unit: "portion", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Blueberry Croffle", recipe_category: "Fruity", ingredient_name: "Chopstick", quantity: 1, unit: "pair", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Blueberry Croffle", recipe_category: "Fruity", ingredient_name: "Wax Paper", quantity: 1, unit: "piece", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Mango Croffle", recipe_category: "Fruity", ingredient_name: "Regular Croissant", quantity: 1, unit: "piece", cost_per_unit: 15, suggested_price: 125 },
  { recipe_name: "Mango Croffle", recipe_category: "Fruity", ingredient_name: "Whipped Cream", quantity: 1, unit: "serving", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Mango Croffle", recipe_category: "Fruity", ingredient_name: "Mango Jam", quantity: 1, unit: "scoop", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Mango Croffle", recipe_category: "Fruity", ingredient_name: "Crushed Grahams", quantity: 1, unit: "portion", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Mango Croffle", recipe_category: "Fruity", ingredient_name: "Chopstick", quantity: 1, unit: "pair", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Mango Croffle", recipe_category: "Fruity", ingredient_name: "Wax Paper", quantity: 1, unit: "piece", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Strawberry Croffle", recipe_category: "Fruity", ingredient_name: "Regular Croissant", quantity: 1, unit: "piece", cost_per_unit: 15, suggested_price: 125 },
  { recipe_name: "Strawberry Croffle", recipe_category: "Fruity", ingredient_name: "Whipped Cream", quantity: 1, unit: "serving", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Strawberry Croffle", recipe_category: "Fruity", ingredient_name: "Strawberry Jam", quantity: 1, unit: "scoop", cost_per_unit: 1.5, suggested_price: 125 },
  { recipe_name: "Strawberry Croffle", recipe_category: "Fruity", ingredient_name: "Chopstick", quantity: 1, unit: "pair", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Strawberry Croffle", recipe_category: "Fruity", ingredient_name: "Wax Paper", quantity: 1, unit: "piece", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Glaze Croffle", recipe_category: "Glaze", ingredient_name: "Regular Croissant", quantity: 1, unit: "piece", cost_per_unit: 15, suggested_price: 79 },
  { recipe_name: "Glaze Croffle", recipe_category: "Glaze", ingredient_name: "Glaze Powder", quantity: 10, unit: "grams", cost_per_unit: 1, suggested_price: 79 },
  { recipe_name: "Glaze Croffle", recipe_category: "Glaze", ingredient_name: "Wax Paper for Glaze", quantity: 1, unit: "piece", cost_per_unit: 0.87, suggested_price: 79 },
  { recipe_name: "Croffle Overload", recipe_category: "Mix & Match", ingredient_name: "Regular Croissant", quantity: 0.5, unit: "piece", cost_per_unit: 15, suggested_price: 99 },
  { recipe_name: "Croffle Overload", recipe_category: "Mix & Match", ingredient_name: "Vanilla Ice Cream", quantity: 1, unit: "Scoop", cost_per_unit: 15.44, suggested_price: 99 },
  { recipe_name: "Croffle Overload", recipe_category: "Mix & Match", ingredient_name: "Overload Cup", quantity: 1, unit: "piece", cost_per_unit: 4, suggested_price: 99 },
  { recipe_name: "Croffle Overload", recipe_category: "Mix & Match", ingredient_name: "Mini Spoon", quantity: 1, unit: "piece", cost_per_unit: 0.5, suggested_price: 99 },
  { recipe_name: "Croffle Overload", recipe_category: "Mix & Match", ingredient_name: "Popsicle Stick", quantity: 1, unit: "piece", cost_per_unit: 0.3, suggested_price: 99 },
  { recipe_name: "Croffle Overload", recipe_category: "Mix & Match", ingredient_name: "Colored Sprinkles", quantity: 1, unit: "portion", cost_per_unit: 2.5, suggested_price: 99 },
  { recipe_name: "Croffle Overload", recipe_category: "Mix & Match", ingredient_name: "Marshmallow", quantity: 1, unit: "portion", cost_per_unit: 2.5, suggested_price: 99 },
  { recipe_name: "Croffle Overload", recipe_category: "Mix & Match", ingredient_name: "Choco Flakes", quantity: 1, unit: "portion", cost_per_unit: 2.5, suggested_price: 99 },
  { recipe_name: "Croffle Overload", recipe_category: "Mix & Match", ingredient_name: "Peanut", quantity: 1, unit: "portion", cost_per_unit: 2.5, suggested_price: 99 },
  { recipe_name: "Mini Croffle", recipe_category: "Mix & Match", ingredient_name: "Chocolate Sauce", quantity: 1, unit: "portion", cost_per_unit: 5, suggested_price: 65 },
  { recipe_name: "Mini Croffle", recipe_category: "Mix & Match", ingredient_name: "Caramel Sauce", quantity: 1, unit: "portion", cost_per_unit: 5, suggested_price: 65 },
  { recipe_name: "Mini Croffle", recipe_category: "Mix & Match", ingredient_name: "Tiramisu", quantity: 1, unit: "portion", cost_per_unit: 5, suggested_price: 65 },
  { recipe_name: "Mini Croffle", recipe_category: "Mix & Match", ingredient_name: "Colored Sprinkles", quantity: 1, unit: "portion", cost_per_unit: 3, suggested_price: 65 },
  { recipe_name: "Mini Croffle", recipe_category: "Mix & Match", ingredient_name: "Marshmallow", quantity: 1, unit: "portion", cost_per_unit: 3, suggested_price: 65 },
  { recipe_name: "Mini Croffle", recipe_category: "Mix & Match", ingredient_name: "Choco Flakes", quantity: 1, unit: "portion", cost_per_unit: 3, suggested_price: 65 },
  { recipe_name: "Mini Croffle", recipe_category: "Mix & Match", ingredient_name: "Peanut", quantity: 1, unit: "portion", cost_per_unit: 3, suggested_price: 65 },
  { recipe_name: "Mini Croffle", recipe_category: "Mix & Match", ingredient_name: "Regular Croissant", quantity: 0.5, unit: "piece", cost_per_unit: 15, suggested_price: 65 },
  { recipe_name: "Biscoff Croffle", recipe_category: "Premium", ingredient_name: "Chopstick", quantity: 1, unit: "pair", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Biscoff Croffle", recipe_category: "Premium", ingredient_name: "Wax Paper", quantity: 1, unit: "piece", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Biscoff Croffle", recipe_category: "Premium", ingredient_name: "Regular Croissant", quantity: 1, unit: "piece", cost_per_unit: 15, suggested_price: 125 },
  { recipe_name: "Biscoff Croffle", recipe_category: "Premium", ingredient_name: "Whipped Cream", quantity: 1, unit: "serving", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Biscoff Croffle", recipe_category: "Premium", ingredient_name: "Biscoff Crushed", quantity: 1, unit: "portion", cost_per_unit: 3.5, suggested_price: 125 },
  { recipe_name: "Biscoff Croffle", recipe_category: "Premium", ingredient_name: "Biscoff", quantity: 1, unit: "piece", cost_per_unit: 3.5, suggested_price: 125 },
  { recipe_name: "Choco Overload Croffle", recipe_category: "Premium", ingredient_name: "Regular Croissant", quantity: 1, unit: "piece", cost_per_unit: 15, suggested_price: 125 },
  { recipe_name: "Choco Overload Croffle", recipe_category: "Premium", ingredient_name: "Whipped Cream", quantity: 1, unit: "serving", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Choco Overload Croffle", recipe_category: "Premium", ingredient_name: "Chocolate Sauce", quantity: 1, unit: "portion", cost_per_unit: 1.75, suggested_price: 125 },
  { recipe_name: "Choco Overload Croffle", recipe_category: "Premium", ingredient_name: "Choco Flakes", quantity: 1, unit: "portion", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Choco Overload Croffle", recipe_category: "Premium", ingredient_name: "Chopstick", quantity: 1, unit: "pair", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Choco Overload Croffle", recipe_category: "Premium", ingredient_name: "Wax Paper", quantity: 1, unit: "piece", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Cookies Cream Croffle", recipe_category: "Premium", ingredient_name: "Regular Croissant", quantity: 1, unit: "piece", cost_per_unit: 15, suggested_price: 125 },
  { recipe_name: "Cookies Cream Croffle", recipe_category: "Premium", ingredient_name: "Whipped Cream", quantity: 1, unit: "serving", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Cookies Cream Croffle", recipe_category: "Premium", ingredient_name: "Crushed Oreo", quantity: 1, unit: "portion", cost_per_unit: 2, suggested_price: 125 },
  { recipe_name: "Cookies Cream Croffle", recipe_category: "Premium", ingredient_name: "Oreo Cookie", quantity: 1, unit: "piece", cost_per_unit: 2, suggested_price: 125 },
  { recipe_name: "Cookies Cream Croffle", recipe_category: "Premium", ingredient_name: "Chopstick", quantity: 1, unit: "pair", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Cookies Cream Croffle", recipe_category: "Premium", ingredient_name: "Wax Paper", quantity: 1, unit: "piece", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Dark Chocolate Croffle", recipe_category: "Premium", ingredient_name: "Regular Croissant", quantity: 1, unit: "piece", cost_per_unit: 15, suggested_price: 125 },
  { recipe_name: "Dark Chocolate Croffle", recipe_category: "Premium", ingredient_name: "Whipped Cream", quantity: 1, unit: "serving", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Dark Chocolate Croffle", recipe_category: "Premium", ingredient_name: "Dark Chocolate Sauce", quantity: 1, unit: "portion", cost_per_unit: 1.75, suggested_price: 125 },
  { recipe_name: "Dark Chocolate Croffle", recipe_category: "Premium", ingredient_name: "Chocolate Crumble", quantity: 1, unit: "portion", cost_per_unit: 1.75, suggested_price: 125 },
  { recipe_name: "Dark Chocolate Croffle", recipe_category: "Premium", ingredient_name: "Chopstick", quantity: 1, unit: "pair", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Dark Chocolate Croffle", recipe_category: "Premium", ingredient_name: "Wax Paper", quantity: 1, unit: "piece", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "KitKat Croffle", recipe_category: "Premium", ingredient_name: "Regular Croissant", quantity: 1, unit: "piece", cost_per_unit: 15, suggested_price: 125 },
  { recipe_name: "KitKat Croffle", recipe_category: "Premium", ingredient_name: "Whipped Cream", quantity: 1, unit: "serving", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "KitKat Croffle", recipe_category: "Premium", ingredient_name: "Chocolate Sauce", quantity: 1, unit: "portion", cost_per_unit: 1.75, suggested_price: 125 },
  { recipe_name: "KitKat Croffle", recipe_category: "Premium", ingredient_name: "Kitkat", quantity: 0.5, unit: "piece", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "KitKat Croffle", recipe_category: "Premium", ingredient_name: "Chopstick", quantity: 1, unit: "pair", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "KitKat Croffle", recipe_category: "Premium", ingredient_name: "Wax Paper", quantity: 1, unit: "piece", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Matcha Croffle", recipe_category: "Premium", ingredient_name: "Regular Croissant", quantity: 1, unit: "piece", cost_per_unit: 15, suggested_price: 125 },
  { recipe_name: "Matcha Croffle", recipe_category: "Premium", ingredient_name: "Whipped Cream", quantity: 1, unit: "serving", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Matcha Croffle", recipe_category: "Premium", ingredient_name: "Matcha Crumble", quantity: 1, unit: "portion", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Matcha Croffle", recipe_category: "Premium", ingredient_name: "Chopstick", quantity: 1, unit: "pair", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Matcha Croffle", recipe_category: "Premium", ingredient_name: "Wax Paper", quantity: 1, unit: "piece", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Nutella Croffle", recipe_category: "Premium", ingredient_name: "Regular Croissant", quantity: 1, unit: "piece", cost_per_unit: 15, suggested_price: 125 },
  { recipe_name: "Nutella Croffle", recipe_category: "Premium", ingredient_name: "Whipped Cream", quantity: 1, unit: "serving", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Nutella Croffle", recipe_category: "Premium", ingredient_name: "Nutella Sauce", quantity: 1, unit: "portion", cost_per_unit: 1, suggested_price: 125 },
  { recipe_name: "Nutella Croffle", recipe_category: "Premium", ingredient_name: "Chopstick", quantity: 1, unit: "pair", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Nutella Croffle", recipe_category: "Premium", ingredient_name: "Wax Paper", quantity: 1, unit: "piece", cost_per_unit: 0.25, suggested_price: 125 },
  { recipe_name: "Dark Chocolate Sauce", recipe_category: "Add-on", ingredient_name: "Dark Chocolate Sauce", quantity: 1, unit: "portion", cost_per_unit: 1.75, suggested_price: 8 }
];

module.exports = recipeData;
