
import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Skeleton } from '@/components/ui/skeleton';
import { Download, FileText, Printer } from 'lucide-react';
import { format } from 'date-fns';
import { fetchDiscountSalesReport, DiscountSalesReport, DiscountType } from '@/services/reports/modules/discountSalesReport';
import { APP_VERSION } from '@/config/appVersion';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface DiscountSalesBookViewProps {
  storeId: string;
  discountType: DiscountType;
  dateRange: {
    from: Date | undefined;
    to: Date | undefined;
  };
}

export function DiscountSalesBookView({ storeId, discountType, dateRange }: DiscountSalesBookViewProps) {
  const [report, setReport] = useState<DiscountSalesReport | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    async function loadReport() {
      if (!storeId || !dateRange.from || !dateRange.to) return;
      
      setIsLoading(true);
      const from = format(dateRange.from, 'yyyy-MM-dd');
      const to = format(dateRange.to, 'yyyy-MM-dd');
      
      const data = await fetchDiscountSalesReport(storeId, discountType, from, to);
      setReport(data);
      setIsLoading(false);
    }

    loadReport();
  }, [storeId, discountType, dateRange]);

  const formatCurrency = (amount: number) => `P${amount.toFixed(2)}`;

  const handleExportPDF = () => {
    if (!report) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(`${report.discountLabel} SALES BOOK`, pageWidth / 2, 15, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(report.storeName, pageWidth / 2, 22, { align: 'center' });
    doc.text(report.storeAddress, pageWidth / 2, 27, { align: 'center' });
    doc.text(`TIN: ${report.tin}`, pageWidth / 2, 32, { align: 'center' });
    
    doc.text(`Period: ${report.dateRange.from} to ${report.dateRange.to}`, pageWidth / 2, 40, { align: 'center' });

    // Transactions table
    if (report.transactions.length > 0) {
      autoTable(doc, {
        startY: 48,
        head: [['Date', 'SI No.', 'Name', 'ID No.', 'Gross Sales', 'Discount', 'VAT Exempt', 'Net Sales']],
        body: report.transactions.map(t => [
          t.date,
          t.receiptNumber,
          t.customerName || '-',
          t.idNumber || '-',
          formatCurrency(t.grossSales),
          formatCurrency(t.discountAmount),
          formatCurrency(t.vatExemptSales),
          formatCurrency(t.netSales),
        ]),
        styles: { fontSize: 8 },
        headStyles: { fillColor: [66, 66, 66] },
      });
    }

    // Summary
    const finalY = (doc as any).lastAutoTable?.finalY || 48;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('SUMMARY', 14, finalY + 15);
    
    doc.setFont('helvetica', 'normal');
    const summaryY = finalY + 22;
    doc.text(`Total Transactions: ${report.summary.totalTransactions}`, 14, summaryY);
    doc.text(`Total Gross Sales: ${formatCurrency(report.summary.totalGrossSales)}`, 14, summaryY + 6);
    doc.text(`Total Discount (${report.discountPercentage}%): ${formatCurrency(report.summary.totalDiscountAmount)}`, 14, summaryY + 12);
    doc.text(`Total VAT Exempt Sales: ${formatCurrency(report.summary.totalVatExemptSales)}`, 14, summaryY + 18);
    doc.text(`Total Net Sales: ${formatCurrency(report.summary.totalNetSales)}`, 14, summaryY + 24);

    // Footer
    doc.setFontSize(8);
    doc.text(`Generated by ${APP_VERSION.name} v${APP_VERSION.version}`, 14, doc.internal.pageSize.getHeight() - 10);
    doc.text(`Printed: ${format(new Date(), 'MM/dd/yyyy HH:mm:ss')}`, pageWidth - 14, doc.internal.pageSize.getHeight() - 10, { align: 'right' });

    doc.save(`${discountType}-sales-book-${report.dateRange.from}-to-${report.dateRange.to}.pdf`);
  };

  const handlePrint = () => {
    window.print();
  };

  if (isLoading) {
    return (
      <Card>
        <CardHeader>
          <Skeleton className="h-6 w-48" />
        </CardHeader>
        <CardContent className="space-y-4">
          <Skeleton className="h-20 w-full" />
          <Skeleton className="h-64 w-full" />
        </CardContent>
      </Card>
    );
  }

  if (!report) {
    return (
      <Card>
        <CardContent className="py-8 text-center text-muted-foreground">
          Unable to load report. Please try again.
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-4 print:space-y-2">
      {/* Header Card */}
      <Card className="print:shadow-none print:border-0">
        <CardHeader className="flex flex-row items-center justify-between print:pb-2">
          <div>
            <CardTitle className="text-lg">{report.discountLabel} Sales Book</CardTitle>
            <p className="text-sm text-muted-foreground">
              {report.storeName} • {report.dateRange.from} to {report.dateRange.to}
            </p>
          </div>
          <div className="flex gap-2 print:hidden">
            <Button variant="outline" size="sm" onClick={handlePrint}>
              <Printer className="h-4 w-4 mr-1" />
              Print
            </Button>
            <Button variant="outline" size="sm" onClick={handleExportPDF}>
              <Download className="h-4 w-4 mr-1" />
              PDF
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
            <div>
              <p className="text-muted-foreground">TIN</p>
              <p className="font-medium">{report.tin || 'N/A'}</p>
            </div>
            <div>
              <p className="text-muted-foreground">Total Transactions</p>
              <p className="font-medium">{report.summary.totalTransactions}</p>
            </div>
            <div>
              <p className="text-muted-foreground">Total Discount ({report.discountPercentage}%)</p>
              <p className="font-medium text-green-600">{formatCurrency(report.summary.totalDiscountAmount)}</p>
            </div>
            <div>
              <p className="text-muted-foreground">Total Net Sales</p>
              <p className="font-medium">{formatCurrency(report.summary.totalNetSales)}</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Summary Card */}
      <Card className="print:shadow-none print:border-0">
        <CardHeader className="print:pb-2">
          <CardTitle className="text-base flex items-center gap-2">
            <FileText className="h-4 w-4" />
            Sales Summary
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">
            <div className="p-3 bg-muted rounded-lg">
              <p className="text-xs text-muted-foreground">Gross Sales</p>
              <p className="text-lg font-bold">{formatCurrency(report.summary.totalGrossSales)}</p>
            </div>
            <div className="p-3 bg-muted rounded-lg">
              <p className="text-xs text-muted-foreground">Discount Amount</p>
              <p className="text-lg font-bold text-green-600">{formatCurrency(report.summary.totalDiscountAmount)}</p>
            </div>
            <div className="p-3 bg-muted rounded-lg">
              <p className="text-xs text-muted-foreground">VAT Exempt Sales</p>
              <p className="text-lg font-bold">{formatCurrency(report.summary.totalVatExemptSales)}</p>
            </div>
            <div className="p-3 bg-muted rounded-lg">
              <p className="text-xs text-muted-foreground">VAT Amount</p>
              <p className="text-lg font-bold">{formatCurrency(report.summary.totalVatAmount)}</p>
            </div>
            <div className="p-3 bg-muted rounded-lg">
              <p className="text-xs text-muted-foreground">Net Sales</p>
              <p className="text-lg font-bold">{formatCurrency(report.summary.totalNetSales)}</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Transactions Table */}
      <Card className="print:shadow-none print:border-0">
        <CardHeader className="print:pb-2">
          <CardTitle className="text-base">Transaction Details</CardTitle>
        </CardHeader>
        <CardContent>
          {report.transactions.length === 0 ? (
            <div className="py-8 text-center text-muted-foreground">
              No {report.discountLabel.toLowerCase()} transactions found for this period.
            </div>
          ) : (
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Date</TableHead>
                    <TableHead>Time</TableHead>
                    <TableHead>SI No.</TableHead>
                    <TableHead>Customer Name</TableHead>
                    <TableHead>ID Number</TableHead>
                    <TableHead className="text-right">Gross Sales</TableHead>
                    <TableHead className="text-right">Discount</TableHead>
                    <TableHead className="text-right">VAT Exempt</TableHead>
                    <TableHead className="text-right">Net Sales</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {report.transactions.map((t) => (
                    <TableRow key={t.id}>
                      <TableCell>{t.date}</TableCell>
                      <TableCell>{t.time}</TableCell>
                      <TableCell className="font-mono">{t.receiptNumber}</TableCell>
                      <TableCell>{t.customerName || '-'}</TableCell>
                      <TableCell className="font-mono">{t.idNumber || '-'}</TableCell>
                      <TableCell className="text-right">{formatCurrency(t.grossSales)}</TableCell>
                      <TableCell className="text-right text-green-600">{formatCurrency(t.discountAmount)}</TableCell>
                      <TableCell className="text-right">{formatCurrency(t.vatExemptSales)}</TableCell>
                      <TableCell className="text-right font-medium">{formatCurrency(t.netSales)}</TableCell>
                    </TableRow>
                  ))}
                  {/* Totals Row */}
                  <TableRow className="bg-muted/50 font-bold">
                    <TableCell colSpan={5}>TOTAL</TableCell>
                    <TableCell className="text-right">{formatCurrency(report.summary.totalGrossSales)}</TableCell>
                    <TableCell className="text-right text-green-600">{formatCurrency(report.summary.totalDiscountAmount)}</TableCell>
                    <TableCell className="text-right">{formatCurrency(report.summary.totalVatExemptSales)}</TableCell>
                    <TableCell className="text-right">{formatCurrency(report.summary.totalNetSales)}</TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Certification/Signature Section for Print */}
      <Card className="print:shadow-none print:border-0">
        <CardContent className="pt-6">
          <div className="grid grid-cols-2 gap-8 mt-8">
            <div className="text-center">
              <div className="border-t border-foreground pt-2 mx-8">
                <p className="text-sm">Prepared By</p>
              </div>
            </div>
            <div className="text-center">
              <div className="border-t border-foreground pt-2 mx-8">
                <p className="text-sm">Verified By</p>
              </div>
            </div>
          </div>
          <p className="text-xs text-muted-foreground text-center mt-6">
            Generated by {APP_VERSION.name} v{APP_VERSION.version} on {format(new Date(), 'MMMM dd, yyyy HH:mm:ss')}
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
